import localFont from "next/font/local";
import "./globals.css";
import Header from "@/components/Header/Header";
import Footer from "@/components/Footer/Footer";
import ContextProvider from "./context/MainContext";
import { Toaster } from "react-hot-toast";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// Set Jost as the primary font
const jostFont = localFont({
  src: "./fonts/Jost-VariableFont_wght.ttf",
  variable: "--font-primary",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${jostFont.variable} ${geistSans.variable} ${geistMono.variable} antialiased`}
        style={{ fontFamily: `var(--font-primary), sans-serif` }}
      >
        <ContextProvider>
          <Header />
          {children}
          <Toaster position="top-center" />
          <Footer />
        </ContextProvider>
      </body>
    </html>
  );
}
